### PR TITLE
Fix bors

### PR DESCRIPTION
**Pull request by Xaeroxe**
This change is [Reviewable](https://reviewable.io/reviews/rustgd/shrev-rs/19)

### CODE REVIEW

**Comment by Rhuagh** [comment]
Need to update Travis.yml:

```
branches:
  only:
    # This is where pull requests from "bors r+" are built.
    - staging
    # This is where pull requests from "bors try" are built.
    - trying
    # Uncomment this to enable building pull requests.
    - master
```

**Comment by Rhuagh** [comment]
It will timeout before this is in place

**Comment by Xaeroxe** [comment]
I get the feeling this won't work until it's on master

**Comment by Rhuagh** [comment]
Yeah, that's likely to be the case

**Comment by Rhuagh** [comment]
Bors r-

**Pull request merged**
