### PR TITLE
Better error message when reader not registered

### LINKED ISSUE #26: Unclear error message when reading from RingBuffer
When reading with a reader id that is not in the ringbuffer, I get a undescriptive panic from this line of RingBuffer.read()
```rust
let reader = &mut meta.readers[reader_id.id];
```
Changing it to
```rust
// I didn't check the docs for the correct method names, but I guess it is clear what I mean :)
let reader = &mut meta.readers.get(reader_id.id).expect("ReaderId not registered: {}", reader_id.id);
```
would tell the programmer more directly what's wrong.

### PR DESCRIPTION
**Pull request by ISibboI**
Fixes #26

---
This change is [Reviewable](https://reviewable.io/reviews/rustgd/shrev-rs/27)

### CODE REVIEW

**Review by torkleyy — APPROVED** [review]
Thanks! This happens if a reader id was created with another storage, maybe add that to the panic?

**Comment by ISibboI** [comment]
Thanks for the feedback! I improved the error message.

I noticed btw that I cannot run rustfmt, because the rustfmt.toml uses the apparently outdated option `reorder_imports_in_groups`. I'm using the most current version of rustfmt-nightly.

**Comment by Xaeroxe** [comment]
rustfmt will still run, it's just noisy.  If you feel so inclined go ahead and either replace that with the new name or just remove the option.

**Review by Xaeroxe — APPROVED** [review]
Nice job!

**Comment by ISibboI** [comment]
Thank you!

> rustfmt will still run, it's just noisy. If you feel so inclined go ahead and either replace that with the new name or just remove the option.

I might just do this in a separate pull request after this one is merged.

**Review by Rhuagh — APPROVED** [review]
bors r+

**Review by torkleyy — APPROVED** [review]
bors r+

**Comment by torkleyy** [comment]
Ah well, you know, it helps enabling CI to merge using bors :smile: 
bors r+

**Pull request merged**
